x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"
services:
  api:
    build: ./api
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    expose:
      - "4000"
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:4000/api/ready').then(r => { if (!r.ok) process.exit(1) }).catch(() => process.exit(1))"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - NODE_ENV=${NODE_ENV}
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379
      - MONGO_URL=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017/${MONGO_DB}?authSource=admin
      - MONGO_DB=${MONGO_DB}
      - PORT=${PORT}
      - CACHE_TTL_SECONDS=${CACHE_TTL_SECONDS}
    logging: *default-logging
    restart: unless-stopped    
  mongo:
    image: mongo:7
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
        - db_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet -u \"$$MONGO_INITDB_ROOT_USERNAME\" -p \"$$MONGO_INITDB_ROOT_PASSWORD\" --authenticationDatabase admin --eval \"db.adminCommand('ping').ok\""]
      interval: 10s
      timeout: 5s
      retries: 5  
    logging:
         <<: *default-logging 
         options:
          max-size: "50m"
          max-file: "5"
    restart: unless-stopped  
  redis:
    image: redis:8
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
        - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli --no-auth-warning -a \"$$REDIS_PASSWORD\" ping | grep -q PONG"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging: *default-logging
    restart: unless-stopped  
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  web:
    build: ./web
    expose:
      - "80"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1/"]
      interval: 10s
      timeout: 5s
      retries: 5 
    logging: *default-logging
    restart: unless-stopped 

  proxy:
     build: ./proxy
     ports:
       - "8080:80"
     depends_on:
       web:
            condition: service_healthy
       api:
           condition: service_healthy
     healthcheck:
        test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1/"]
        interval: 10s
        timeout: 5s
        retries: 5  
     logging: *default-logging
     restart: unless-stopped 


volumes:
  db_data:
  redis_data:
